---
- hosts: localhost
  connection: local
  tasks:
    - name: Create a resource group
      azure_rm_resourcegroup:
        name: table1jyansiblerg
        location: japanwest
      register: rg
    - debug:
        var: rg
